### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by bradyespey** [NoahCardoza/minty#1]
I get a cookie expired message each time I try this.

**Comment by NoahCardoza** [comment]
Sorry! Just saw this!

I took a quick look into it and it seems that Mint updated their API which is why it's breaking I believe.

If I get a chance I'll see if I can fix it. It will probably have to wait till next weekend at the earliest.

If you could still use it let me know and I'll bump it up on my priority list.

**Comment by bradyespey** [comment]
No rush! I ended up trying out Monarch instead, but may look back into Mint down the road.

**Comment by NoahCardoza** [comment]
Not a bad choice, I've been eyeing them myself. 

To anyone else who might see this thread: Since Heroku discontinued their free tier instanced I'll most likely not be looking into this in the future unless there is a particular demand.
